spring.application.name=testeAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/teste_api
spring.datasource.username=postgres
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true